mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.bupt.godxian.charging.mybatis.entity
server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/db_name
        username: username
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver